version: '3.8'

services:
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.0
    command: ["milvus", "run", "standalone"]
    ports:
      - "${MILVUS_PORT}:19530"
      - "9091:9091"
    environment:
      ETCD_ENDPOINTS: "etcd:2379"
      MINIO_ADDRESS: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MILVUS_LOG_LEVEL: "debug"
    depends_on:
      - etcd
      - minio
    volumes:
      - milvus_data:/var/lib/milvus

  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    environment:
      ETCD_DATA_DIR: "/etcd-data"
    ports:
      - "2379:2379"
      - "2380:2380"
    command:
      - etcd
      - --name=etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd:2380
      - --initial-cluster=etcd=http://etcd:2380
      - --initial-cluster-state=new
    volumes:
      - etcd_data:/etcd-data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  rag_system:
    container_name: rag
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - dotenv_files/.env
    depends_on:
      - milvus
    ports:
      - "8001:8080"
    volumes:
      - ./logs:/logs


volumes:
  milvus_data:
  etcd_data:
  minio_data:
  logs: